### ISSUE TITLE
Fails to build on ARM

### ISSUE THREAD

**Issue by vinipsmaker** [danburkert/fs2-rs#1]
```
[rust@vinipsmaker-pi fs2-rs]$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading tempdir v0.3.4
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.4
   Compiling winapi v0.2.5
   Compiling kernel32-sys v0.2.1
   Compiling fs2 v0.2.2 (file:///home/rust/Projects/fs2-rs)
src/unix.rs:117:26: 117:39 error: mismatched types:
 expected `*const u8`,
    found `*const i8`
(expected u8,
    found i8) [E0308]
src/unix.rs:117         if libc::statvfs(cstr.as_ptr(), &mut stat) == -1 {
                                         ^~~~~~~~~~~~~
src/unix.rs:117:26: 117:39 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `fs2`.

To learn more, run the command again with --verbose.
```

**Comment by danburkert** [comment]
@vinipsmaker thanks for the report!  I don't have an android environment to test on, so if you could try again and make sure everything is compiling as expected I can go ahead and push a new version to crates.io.

**Comment by vinipsmaker** [comment]
> I don't have an android environment to test on, so if you could try again and make sure everything is compiling as expected I can go ahead and push a new version to crates.io.

Neither do I. I test these things on ArchLinux ARM/Raspberry Pi.

Anyway, I tested again and your fix works. Thank you.

However, I did a second thing. I updated rust to the latest stable (1.6.0) and tried to compile without your fixing commit. I noticed that your patch wasn't needed if we're using the latest stable Rust. So you can revert the commit if you wish.
