### ISSUE TITLE
fcntl instead of flock

### ISSUE THREAD

**Issue by dignifiedquire** [danburkert/fs2-rs#10]
I was looking into using this module but need for my locks on unix the properties of fcntl instead of flock. So I was wondering if you would accept a PR that adds an option to switch to fcntl.

**Comment by danburkert** [comment]
Hey @dignifiedquire, I'd certainly be interested, but when I was researching the subject I found that `fcntl` had behavior that wasn't as cross platform consistent as flock.  What are the properties that you are looking for?

**Comment by danburkert** [comment]
Closing for non-activity, feel free to re-open with new information.

**Comment by asayers** [comment]
FYI [this post](https://apenwarr.ca/log/20101213) is a wealth of information about `flock` and `fcntl` locks, and their relative reliability/portability.
