### ISSUE TITLE
0.4.0 doesn't compile for 32-bit targets

### ISSUE THREAD

**Issue by japaric** [danburkert/fs2-rs#13]
```
$ cargo clone --vers '0.4.0' fs2 && cd $_
$ cargo build --target i686-unknown-linux-gnu
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.18
   Compiling fs2 v0.4.0 (file:///home/japaric/tmp/fs2)
error[E0308]: mismatched types
   --> src/unix.rs:128:41
    |
128 |                 allocation_granularity: stat.f_frsize,
    |                                         ^^^^^^^^^^^^^ expected u64, found u32

error: aborting due to previous error

error: Could not compile `fs2`.

To learn more, run the command again with --verbose.
```

**Comment by danburkert** [comment]
I'll push a fix for this soon, but I can't repro on travis.  Could you provide more details about the platform so that this might be covered through fs2's CI in the future?

**Comment by japaric** [comment]
> I can't repro on travis.

AFAICT, your travis configuration is only testing 64-bit Linux and 64-bit osx.

You can test 32-bit targets via cross compilation. In a nutshell, you want to set up a new Travis job to run these commands:

```
# test 32-bit Linux on 64-bit Linux
$ curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly -y
$ rustup target add i686-unknown-linux-gnu
$ cargo build --target i686-unknown-linux-gnu
$ cargo test --target i686-unknown-linux-gnu
```

**Comment by danburkert** [comment]
Sorry - forgot to mention that I started a travis run with i686: https://travis-ci.org/danburkert/fs2-rs/builds/187282453, with these changes: https://github.com/danburkert/fs2-rs/commit/0e7edb95b8eee904d7c3be84f76358ddb244ca60.  I'll try out your instructions as well locally.

**Comment by danburkert** [comment]
Just pushed 0.4.1 that should fix the issue.  I'm still not sure why travis' i686 build didn't repro, I'm worried this could regress in the future because of that (it already regressed sometime since 0.3).

**Comment by japaric** [comment]
Hmm, I don't think this:

```
env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
```

has any effect on the build. Where did you get this `ARCH` idea?

**Comment by danburkert** [comment]
Yah, that was leftover from some old travis scripts I'd based off `libc` and then promptly forgot that it was only 1/2 the story.  Thanks.
