### ISSUE TITLE
Build fails because of mismatched types for posix_fallocate.

### ISSUE THREAD

**Issue by ivegotasthma** [danburkert/fs2-rs#4]
I just did a `multirust update` and `cargo clean && cargo build`.

Rustc version -   

    ico@arch ~ $ rustc --version
    rustc 1.8.0-nightly (57c357d89 2016-02-16)

with the error message

    Compiling fs2 v0.2.2
    /home/ico/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/fs2-0.2.2/src/unix.rs:63:67: 63:79 error: mismatched types:
     expected `i64`,
        found `u64` [E0308]
    /home/ico/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/fs2-0.2.2/src/unix.rs:63     let ret = unsafe { libc::posix_fallocate(file.as_raw_fd(), 0, len as off_t) };
                                                                                                                                                                                      ^~~~~~~~~~~~
    /home/ico/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/fs2-0.2.2/src/unix.rs:63:67: 63:79 help: run `rustc --explain E0308` to see a detailed explanation
    error: aborting due to previous error

I checked out `libc`'s [source](https://github.com/rust-lang/libc/search?utf8=%E2%9C%93&q=posix_fallocate) but the type looks to be in order.

**Comment by danburkert** [comment]
Please update to version 0.2.3.  Thanks for the report!
