### ISSUE TITLE
FileExt::duplicate is the same as File::try_clone

### ISSUE THREAD

**Issue by sfackler** [danburkert/fs2-rs#9]
Just a heads up 😃

**Comment by danburkert** [comment]
Ah, so it is.  May just leave it here, since it works on older Rusts as well.  I would love if everything in this crate would eventually move into `std` (although I don't have my hopes up for file locks).  I'll update the docs to encourage use of `try_clone` when I get a chance.

**Comment by danburkert** [comment]
added to doc by 206defe16b27079cedea4b01a494cc2d1588f5a0
